### ISSUE TITLE
Adding directives to custom scalar types

### ISSUE THREAD

**Issue by Alxandr** [ChilliCream/graphql-platform#1380]
**Is your feature request related to a problem? Please describe.**
I'm trying to add a directive to a custom scalar type. In GQL this would look like such:

```graphql
directive @test on SCALAR

scalar CustomerNumber @test
```

**Describe the solution you'd like**
I'm not sure how best to solve this. As far as I can tell, the `ScalarType` type has a `Directive` property (with a private setter) which it always instantiates using `Array.Empty()` for the directives (https://github.com/ChilliCream/hotchocolate/blob/e7ccddd7bab7f3ed15c6b712666262e491e6fa18/src/Core/Types/Types/Scalars/ScalarType.cs#L245). Maybe adding a virtual `GetDirectiveDefinition` or something like that so deriving classes has a chance at adding directives is the best solution?

**Describe alternatives you've considered**
I'm not sure if any good alternatives exist - except maybe going schema first. But I would like for my code to define my schema.

**Comment by michaelstaib** [comment]
This is on our list for version 11. We originally wanted to add it with 10 but have moved it since we did want to do some more refactoring on the scalar side.

**Comment by tobias-tengler** [comment]
To my knowledge this should work with the current version. Closing this, but feel free to re-oprn, if you still encounter problems.

**Comment by michaelstaib** [comment]
This is still broken. We did not invest time in it since it's a rare case in which you need that.

**Comment by AntonC9018** [comment]
The larger issue is that it doesn't allow configuration like all the other things like types and directives do, with descriptors and all of the APIs around that. @michaelstaib is this something we want for scalars as well? I mean, I personally think the whole descriptor design is kind of flawed, because of the enormous magnitude of code duplication that has to happen to accommodate it, but if you disagree or feel like we're not ready for a rewrite, I can duplicate the setup for scalars as well if you want.
Also, is this something Skimmed aims to solve?
