### ISSUE TITLE
Is more fine grained than policy authorization possible? 

### ISSUE THREAD

**Issue by ademchenko** [ChilliCream/graphql-platform#3456]
The issue being described is also mentioned in [that](https://github.com/ChilliCream/hotchocolate/issues/2150) task discussion.

So, we have a real scenario which is very usual.

A user has a big number of fine-grained permissions like "allowViewPayments",  "allowViewStats", "allowViewUsers", etc etc. There are really many such permissions. 

GraphQL resources are authorized by permissions like:
1. resource A is allowed to access if the user has "A" permission
2. resource B is allowed to access if the user has "A" **and** "B" permission
3. resource C is allowed to access if the user has "A" **or** "B" permission

There are two available options in case of authorization in HotChocolate: roles and policies. It's obvious that the roles approach is not relevant to our case. But the use of policies is also problematic even in the first (the easiest) example if there are many permissions in the system. In that case, we need to create lots of policies like "hasAPermission", "hasBPermission", etc and handle each of that policy. It is very inconvenient.

I was thinking about the attribute "HasPermissions(string[] permissions)" but after some research, I don't see that's really possible. I was thinking about AuthorizeObjectFieldDescriptorExtensions.Authorize extension but it works with the policy name string but not with the Policy object (or requirement object or something similar) and it's impossible to pass parameters like:
.Authorize(new PermissionPolicy("hasAPermission")).

So, could you say what is the easiest way to implement the "permissions based" authorization?

**Comment by ademchenko** [comment]
@michaelstaib, any movements?

**Comment by jamiewinder** [comment]
I'm looking into the same issue. Is there a way to do this?

**Comment by PascalSenn** [comment]
Our main goal is to protect objects/entties rather than resolvers. You can btw already implement your custom IAuthroizationHandler.

**Comment by onionhammer** [comment]
Same here... this seems rather tricky to do with HC

**Comment by onionhammer** [comment]
Copied from 5237 for discussion:

Is your feature request related to a problem?
The problem is resource-based authorization, where you need to download a resource (from, say, a database) based on the query and context and then check the authorization.

The guidance from Microsoft here is to use imperative auth rather than a declarative attribute ([Authorize]). This is supported in ASPNET Core with the IAuthorizationService, and you can call it from HotChocolate, but there's nothing to do with that information but throw some custom exception?

https://docs.microsoft.com/en-us/aspnet/core/security/authorization/resourcebased?view=aspnetcore-6.0

I am building a multi-tenant application with HotChocolate, and authorizing users for specific resources right now isn't straightforward to me. I have worked around it by basically using the 'Context' in an authorization handler and checking the type with '.Parent', but it feels hacky.. also there doesnt appear to be a good way to go up the chain of 'ancestors', for example a '.GetParentOfType' where it keeps going up the tree of ancestors until it finds the parent of type T.

The solution you'd like
It would be awesome if this scenario was better supported, or if it is well supported (showing my lack of knowledge here), better documented here ( https://chillicream.com/docs/hotchocolate/security/authorization ).

**Comment by michaelstaib** [comment]
@onionhammer 

> For mutations... middleware attributes dont appear to work so probably even more hacky

there is no difference in mutations and queries.

**Comment by zivfuture** [comment]
#5442

**Comment by michaelstaib** [comment]
We abstracted the IAuthorizationHandler in Hot Chocolate and you can now plug in your own system. Also with 13 we track now objects that need to be authorized instead of simple field authorization.

**Comment by onionhammer** [comment]
@michaelstaib that sounds amazing! Is there an example of how to accomplish this in the v13 docs yet?

**Comment by michaelstaib** [comment]
We are working on this.

**Comment by onionhammer** [comment]
@michaelstaib Awesome. I'm looking to basically clean up the mess I made with my current GraphQL server and upgrade to v13 soon, hopefully with better authorization code and fewer hacks around JsonExtensionData :D
