### ISSUE TITLE
Record struct are not supported for custom runtime types

### ISSUE THREAD

**Issue by repne** [ChilliCream/graphql-platform#4467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a strongly typed id implemented using the new record struct data structure but when I try to expose it from my graphql scheme I'm getting an error. This is working fine for other custom types, including the same data structure implemented as a record class. Is there any extra setup involved that I'm missing?

### Steps to reproduce

I have the following set up code:

```
.AddTypeConverter<string, MyCustomId>(from => MyCustomId.Create(from))
.AddTypeConverter<MyCustomId, string>(from => from.Value)
.BindRuntimeType<MyCustomId, StringType>()
```

If MyCustomId is defined as:

`
public record class MyCustomId(string Value);
`

Everything works fine.

If MyCustomId is defined as:

`
public readonly record struct MyCustomId(string Value);
`

I get the following error:
`
The type of the member Id of the declaring type ViewModel is unknown
 (HotChocolate.Data.Filters.FilterInputType<MyCompany.MyViewModel>)'
`

### Product

Hot Chocolate

### Version

12.3.0

**Comment by michaelstaib** [comment]
I will write a test for this.

**Comment by PascalSenn** [comment]
So for filtering this is a bit different. The mapping of scalar to filter input type is similar but not exactly the same as on the schema builder. While in most cases this works fine, binding a runtime type like this, will not work. 

With #5760  you can use structs for filtering, but it would infer it as an "object" rather than a scalar. With #5759 there is a bit more documentation around how to bind and override the filters. 

In your case this will work:
```csharp
services
    .AddGraphQLServer()
    .AddFiltering(x => x.BindRuntimeType<MyCustomId, StringOperationFilterInputType>())
    .AddTypeConverter<string, MyCustomId>(from => new MyCustomId(from))
    .AddTypeConverter<MyCustomId, string>(from => from.Value)
    .BindRuntimeType<MyCustomId, StringType>()
   ...
```
