### ISSUE TITLE
Unable to define List<T> default value on an input type

### ISSUE THREAD

**Issue by bass2008** [ChilliCream/graphql-platform#5135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Defining a default value for an List<T> property on an input type doesn't appear on the schema.
The DefaultValue attribute fine works with boolean value, but it doesn't work with default(List<T>)

### Steps to reproduce

[DefaultValue(true)]
public bool IsActive { get;  set; }  // works! Apears on the schema

[DefaultValue(default(List< Foo>))]
public List< Foo> Bar { get; set; } = new();   // Doesn't apear on the schema

### Additional Context?

Similar problem:
https://github.com/ChilliCream/hotchocolate/issues/1862

### Product

Hot Chocolate

### Version

12.9.0

**Comment by michaelstaib** [comment]
The issue here is that dotnet does not allow for value creation in attribute parameters. However, you can use the fluent API to do this.

While creating a small example for you I saw a couple of pitfalls here which we will address in a patch release.

The main thing is to use the AST to describe the default value as it is more precise than the .NET runtime value. The issue here is that a dotnet object has no distinction between `null` and not set. I will leave this issue open as an enhancement for 13.

[ListDefaultValue.zip](https://github.com/ChilliCream/hotchocolate/files/8883613/ListDefaultValue.zip)
