### ISSUE TITLE
UseRequest is forcing to use the UseDefaultPipeline otherwise the application simply does not work.

### ISSUE THREAD

**Issue by pedro-coelho-ff** [ChilliCream/graphql-platform#5862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

When creating a new project and by simply doing something like this:

```
.UseRequest(next => async context => 
            {
                await next(context);
            })
```

The banana cake pop cannot fetch the schema no error is visible in the console and also nothing is visible on the banana cake pop the only place where the error is visible is on the network.

`{"errors":[{"message":"Unexpected Execution Error","extensions":{"message":"Operation is not valid due to the current state of the object.","stackTrace":"   at HotChocolate.Execution.RequestExecutor.ExecuteAsync(IQueryRequest request, CancellationToken cancellationToken)\r\n   at HotChocolate.AspNetCore.MiddlewareBase.ExecuteSingleAsync(HttpContext context, IRequestExecutor requestExecutor, IHttpRequestInterceptor requestInterceptor, IServerDiagnosticEvents diagnosticEvents, GraphQLRequest request, GraphQLRequestFlags flags)\r\n   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context)"}}]}`

By doing this 

`.UseRequest(next => async context => 
            {
                await next(context);
            });
            .UseDefaultPipeline();`

The application works fine and the banana cake pop is able to fetch schema.

I think this is not the intended behavior where one to register a HC middleware needs to also say explicit to use the defaultpipeline.

### Steps to reproduce

1. Create a new graphql application
2. Register a middleware
3. The error occurs
4. After the middleware use the `.UseDefaultPipeline()`
5. The application works fine.

### Version

13.0.1/13.0.2

**Comment by michaelstaib** [comment]
This is expected behavior ...

We have three different pipelines in Hot Chocolate
- UseDefaultPipeline()
- UseAutomaticPersistedQueryPipeline
- UsePersistedQueryPipeline

Depending on the modules you use there are more.

When you specify a custom request pipeline you MUST specify the pipeline you want to use and also the when you custom middleware is to happen ... is it chained in at the end or at the beginning. It might also be that you want to respecify the pipeline completely. We have that quite often in projects that customize the execution behavior in this level.

`UsePersistedQueryPipeline` is not a block as you might think ... its just lots of `UseRequest` put together.

So, the behavior you outlined is the behavior we designed.
