### ISSUE TITLE
Extending object types by using an interface as a parent type does not add extensions to interface type

### ISSUE THREAD

**Issue by anadale** [ChilliCream/graphql-platform#5974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

When using annotation based approach to extend object types it is common to specify an interface instead of concrete type. However, while specified extensions are reflected in corresponding ObjectTypes, they are not reflected in InterfaceType, if any. Is it by design or should be fixed?

### Steps to reproduce

Create a simple setup:

```csharp
[InterfaceType] // Mark it so it gets to the schema
public interface IFile
{
    string Id { get; }
}

public class FatFile : IFile
{
    public string Id => "fat";
}

public class SkinnyFile : IFile
{
    public string Id => "skinny";
}

[ExtendObjectType<IFile>]
public static class FileExtensions
{
    public static string GetUrl([Parent] IFile file) => $"/path/to/{file.Id}";
}
```

Here is the fragment of the resulting schema:

```graphql
type FatFile implements IFile {
    id: String!
    url: String!
}

type SkinnyFile implements IFile {
    id: String!
    url: String!
}

interface IFile {
    id: String!
    # url: String! is not here!
}
```

As you see, url field declaration doesn't get into schema despite the fact that extension was for the interface (and has correctly landed into object types).

### Version

13.0.5

**Comment by michaelstaib** [comment]
That is expected since ExtendObjectType only extens object types ... it essentially represents the graphql syntax

```graphql
extend type SkinnyFile {
  url: String
}
```

**Comment by michaelstaib** [comment]
We have not implemented something similar for interfaces because I could not see the use case for it so far. We can have a look at it at some point.

**Comment by michaelstaib** [comment]
But ... you can probably do that yourself with a type interceptor.

**Comment by anadale** [comment]
Nice idea, will try that, thank you!

**Comment by zmerdev** [comment]
> We have not implemented something similar for interfaces because I could not see the use case for it so far. We can have a look at it at some point.

Here is a use case.  I work at a trucking company. And we send drivers on different kinds of trips. So we have a trip base class (abstract).

``` c#

public abstract class Trip
{
    public int Id { get; set }
    public ICollection<Stop> Stops{ get; set; } = null!;
    ...
}

public class DeliveryTrip : Trip
{
    public Customer Customer { get; set }
}

public class PickupTrip : Trip
{
    public Supplier Supplier { get; set }
}

public class Stop
{
    public Trip Trip{ get; set; } = null!;
    public int Order { get; set; }
    public double Miles { get; set; }
    ...
}
```
Now to get the total miles of a trip we'd need to aggregate all the miles of each stop together.  We could push this off to the client, but then every client would need to have the knowledge of how to properly aggregate this field.  We'd also lose the ability filter on this extended field.  So if we wanted to find all trips over 2000km that would be impossible since the base class doesn't actually hold the field.

It also means that if i added an extension for TotalMiles in my graph query we have to explicit union each inherited type, which for some of our interfaces is a dozen or more classes.

```
trips(){ 
  nodes{
    Id
    ... on DeliverTrip {
        TotalMiles
    }
    ... on PickupTrip {
        TotalMiles
    }
  }
```

It seems to me all this behavior would be significantly improved if the interface class held the extended field rather than its children.
