### ISSUE TITLE
Suppress warning CS1591: Missing XML comment in autogenerated code  

### ISSUE THREAD

**Issue by kirekocev3Shape** [ChilliCream/graphql-platform#5987]
### Product

Hot Chocolate

### Is your feature request related to a problem?

HotChocolate.Types.Analyzers generate code ([Data Loaders](https://chillicream.com/blog/2023/02/08/new-in-hot-chocolate-13#dataloader), [Type Auto Registration](https://chillicream.com/blog/2023/02/08/new-in-hot-chocolate-13#type-auto-registration), etc) that can be publicly visible. This autogenerated code produces warnings type CS1591: Missing XML comment and it can not be suppressed.

### The solution you'd like

I would like the autogenerated code to have directives that suppress the specified warnings.

**Comment by SeijiSuenaga** [comment]
For what it's worth, you can suppress these warnings using an .editorconfig file, for example:
```ini
[**/Generated/**]
dotnet_diagnostic.CS1591.severity = none
```
If you're using Visual Studio, you might be able to [disable all warnings](https://learn.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2022#configure-generated-code) instead of specific ones:
```ini
[**/Generated/**]
generated_code = true
```
but I haven't gotten that to work with `dotnet` CLI.

**Comment by RobTF** [comment]
Hi @SeijiSuenaga,

Unfortunately the suppression in `.editorconfig` does not work with source generated files. If you try to filter suppression directives by the filename (e.g. in a `[*.g.cs]` section) it is ignored for these files.

I also ran into this issue with Godot and their source generators. It currently requires the generated code to add a `#pragma' directive in order to suppress analysis issues.

**Comment by SeijiSuenaga** [comment]
@RobTF that's odd because the first example I posted does work for me with .NET SDK 6.0.408 and VS Code with Roslyn analyzers enabled. 🤔  I get no warnings with that .editorconfig, and lots of warnings without it.

**Comment by RobTF** [comment]
Interesting... ill give it a try again tomorrow. If i get no joy ill push to a public repo so perhaps we could compare?

**Comment by SapiensAnatis** [comment]
Is a fix for this likely to make it into a release in the near future? This is making me reconsider whether to use the source generators in our project -- they are great, but it looks like I would have to suppress the doc rules project-wide, because I couldn't get any editorconfig rules to be respected and we have our CI build our code with warnings set to errors.

**Comment by SapiensAnatis** [comment]
Turns out you can suppress messages in just the generated code using `.globalconfig` and then re-enabling the warning in `.editorconfig`

https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-files#global-analyzerconfig
