### ISSUE TITLE
Banana Cake Pop: Support local documents

### ISSUE THREAD

**Issue by kmcclellan** [ChilliCream/graphql-platform#6143]
### Product

Banana Cake Pop

### Is your feature request related to a problem?

I want to use the file upload feature of Banana Cake Pop to send files to an internal (non-public) Hot Chocolate wep app. For security reasons (and convenience), I want to attach files from my local machine. I don't want to have to log in or have my personal documents stored on ChilliCream and/or cloud servers.

It would also be nice to save query operations written in the UI to the filesystem instead of cookies.

### The solution you'd like

The documents pane in Banana Cake Pop lets you link documents and/or folders from the local filesystem, without having to sign in.

**Comment by michaelstaib** [comment]
The documents are not stored in cookies... we keep them in the local storage of the browser. As towards binary files for upload tests. You need to sign in, but these files will never be synced. The will always stay local. Only API documents or GraphQL documents are synced.

While we will not implement a mapping of your local file system we are soon allowing companies to host their own BCP backend and then all GraphQL documents are synced with your company instead of the chillicream cloud. Also the authentication is then handled by you company.

I will close this issue as we have different plans as outlined.
