### ISSUE TITLE
AUTH_NOT_AUTHORIZED returned when expecting AUTH_NOT_AUTHENTICATED

### ISSUE THREAD

**Issue by epbensimpson** [ChilliCream/graphql-platform#6228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

When a user is not authenticated and attempts to access a type/field protected by `[Authorize]`, they receive an `AUTH_NOT_AUTHORIZED` error instead of `AUTH_NOT_AUTHENTICATED`

This is in contradiction to the [documentation ](https://github.com/ChilliCream/graphql-platform/blob/5e1cfa8f6f34d8c2f62531fd280b032bd2b20cbf/website/src/docs/hotchocolate/v13/security/authorization.md?plain=1#L131) which indicates this should result in `AUTH_NOT_AUTHENTICATED`.

We need to be able to differentiate between not authenticated and not authorized so we can have the client re-authenticate if necessary.

### Steps to reproduce

1. Set up server with a basic query with `[Authorize]` on a type:

```csharp
using HotChocolate.Authorization;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddAuthentication();
builder.Services.AddAuthorization();

builder.Services
    .AddGraphQLServer()
    .AddAuthorization()
    .AddQueryType<Query>();

var app = builder.Build();

app.UseRouting();
app.UseAuthentication();
app.UseAuthorization();
app.MapGraphQL();
app.Run();

public class Query
{
    public User GetUser => new();
}

[Authorize]
public class User
{
    public string Name => "Foo";
}
```

2. Execute query:

```graphql
query {
  getUser {
    name
  }
}
```

3. Observe response:

```json
{
  "errors": [
    {
      "message": "The current user is not authorized to access this resource.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "getUser"
      ],
      "extensions": {
        "code": "AUTH_NOT_AUTHORIZED"
      }
    }
  ]
}
```

### Version

13.1.0

**Comment by epbensimpson** [comment]
Would you consider unsealing `DefaultAuthorizationHandler` and making it public, and making the interface methods `virtual` so I can extend the default handler without having to write one from scratch?

**Comment by hundreder** [comment]
@epbensimpson 
I ran into same problem. Do you have any suggestion on how to implement new CustomAuthorizationHandler, so not to cause any other issue?

**Comment by doeringp** [comment]
You could workaround the problem by implementing an [IErrorFilter](https://chillicream.com/docs/hotchocolate/v10/execution-engine/error-filter) that translates `AUTH_NOT_AUTHORIZED` error codes to `AUTH_NOT_AUTHENTICATED` errors in case the user is not authenticated. But I think it isn't the right place to solve the problem.

It would be great if we could extend Hot Chocolate's `DefaultAuthorizationHandler` instead of implementing our own IAuthorizationHandler from scratch.

**Comment by epbensimpson** [comment]
@hundreder Here's a link to a gist with the changes: https://gist.github.com/epbensimpson/401c2418b8f59ed55461d5d001397fff

Changes are at line 77-88 and line 113-134

**Comment by huysentruitw** [comment]
Just saw that the bug-tag was removed after creating my PR 🤦‍♂️ Anyway, we've stumbled across the same issue and since the [AuthorizeMiddleware supports this state](https://github.com/ChilliCream/graphql-platform/blob/main/src/HotChocolate/Core/src/Authorization/AuthorizeMiddleware.cs#L107), I think it's logical that the AspNetCore implementation correctly returns `NotAuthenticated` when needed.

**Comment by dcby** [comment]
This is how I currently solve this problem.

```cs
internal class ErrorFilter(IServiceProvider serviceProvider) : IErrorFilter
{
  public IError OnError(IError error)
  {
    if (error.Code == "AUTH_NOT_AUTHORIZED")
    {
      // if error code is AUTH_NOT_AUTHORIZED then check if user is authenticated
      // if he isn't then swap error code to AUTH_NOT_AUTHENTICATED
      IHttpContextAccessor httpContextAccessor = serviceProvider.GetRequiredService<IHttpContextAccessor>();
      HttpContext context = httpContextAccessor.HttpContext ?? throw new InvalidOperationException();
      if (context.User.Identity?.IsAuthenticated != true)
      {
        return error.WithCode("AUTH_NOT_AUTHENTICATED");
      }
    }

    return error;
  }
}
```

Don't forget to register the `ErrorFilter`.
```cs
services
  .AddGraphQLServer()
  .AddAuthorization()
  .AddErrorFilter<ErrorFilter>()
  ...
```

**Comment by huysentruitw** [comment]
While that works, it feels "hacky" to resolve the `HttpContext` inside the error-filter IMO. Our use-case is to convert it to a correct HTTP status code. @michaelstaib @PascalSenn any chance you guys can have a look at my PR to fix this? This is a really important issue as a client (front-end) must know the difference in order to know if the JWT needs to be refreshed, the user needs to re-login or if it's a authorization issue.

```C#
private static IError? TransformErrorForAuthn(IError error)
{
    // TODO Below distinction currently doesn't work, because HotChocolate returns NotAuthorized in both cases.
    // Keep an eye on https://github.com/ChilliCream/graphql-platform/issues/6228 
    return error.Code switch
    {
        ErrorCodes.Authentication.NotAuthorized => error
            .SetExtension("statusCode", (int)HttpStatusCode.Forbidden),
        ErrorCodes.Authentication.NotAuthenticated => error
            .SetExtension("statusCode", (int)HttpStatusCode.Unauthorized),
        _ => null,
    };
}
```
