### ISSUE TITLE
File uploads break in HotChocolate 13.2.0/13.2.1

### ISSUE THREAD

**Issue by robindv** [ChilliCream/graphql-platform#6246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

When uploading a file the GraphQL server returns a 404 Not found starting HotChocolate 13.2.0. It worked in previous version of HC.

### Steps to reproduce

I created a mini-project including a curl-script in order to reproduce it: https://github.com/robindv/hc-upload-bug

After checking out the repo you can revert the project to HC 13.1.0 to see it working.

### Version

13.2.0

**Comment by tobias-tengler** [comment]
You now need to add the following header to your HTTP Request: `GraphQL-Preflight: 1`.
More info on why this was done: https://github.com/jaydenseric/graphql-multipart-request-spec#security

**Comment by robindv** [comment]
@tobias-tengler thanks for your answer. Only thing I'm wondering: why isn't a breaking change like this not part of a new major version and documented as such? 

I always follow migration guides like this one: https://chillicream.com/docs/hotchocolate/v13/migrating/migrate-from-12-to-13 and that makes using Hot Chocolate a great experience. This is the first time a minor update broke my application.

**Comment by tobias-tengler** [comment]
@robindv First of all sorry for the inconvenience. I think it wasn't shipped as a major update, because it's a security concern and couldn't wait for the next major update. But I agree, we should have shipped this as part of a major release with clear messaging around the change.

@dylanbarquilla Can you please open a new ticket for Strawberry Shake? Thanks. 
I think you should be able to work around it by configuring the `GraphQL-Preflight` header on the HTTP Client. This will include it in every request, which isn't ideal, but should fix the issue at least.
