### ISSUE TITLE
Hot Chocolate file upload is broken

### ISSUE THREAD

**Issue by kmcclellan** [ChilliCream/graphql-platform#6304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I used to be able to use the ["upload" scalar](https://chillicream.com/docs/hotchocolate/v13/server/files) in a Hot Chocolate GraphQL API. After updating HC to 13.2, multi-part form data requests are returning a 404.

### Steps to reproduce

1. Run a Hot Chocolate web app supporting the upload scalar.

```csharp
using HelloGql;

var builder = WebApplication.CreateBuilder();
builder.Services.AddGraphQLServer()
    .AddType<UploadType>()
    .AddQueryType<FileQueries>();

await using var app = builder.Build();
app.MapGraphQL();
await app.RunAsync();

namespace HelloGql
{
    public class FileQueries
    {
        public string MeasureFile(IFile file)
        {
            return $"File is {file.Length} bytes";
        }
    }
}
```

2. Try to upload a file using either Banana Cake Pop or custom script (e.g. powershell).

```powershell
Invoke-WebRequest -Uri "http://localhost:5000/graphql" -Method "POST" -ContentType "multipart/form-data; boundary=BOUNDARY" -Body "--BOUNDARY`r`nContent-Disposition: form-data; name=`"operations`"`r`n`r`n{ `"query`":`"query(`$file: Upload!) { measureFile(file: `$file) }`",`"variables`": { `"file`": null } }`r`n--BOUNDARY`r`nContent-Disposition: form-data; name=`"map`"`r`n`r`n{ `"0`": [ `"variables.file`" ] }`r`n--BOUNDARY`r`nContent-Disposition: form-data; name=`"0`"; filename=`"hello.txt`"`r`nContent-Type: text/plain`r`n`r`nHello world!`r`n--BOUNDARY--`r`n"
```

### Relevant log output (Banana Cake Pop)

```json
{
  "name": "ServerParseError",
  "statusCode": 404,
  "statusText": "Not Found",
  "bodyText": ""
}
```

### Version

13.2.1

**Comment by kmcclellan** [comment]
Seems to be the relevant change: https://github.com/ChilliCream/graphql-platform/compare/13.1.0...13.2.0#diff-e6b300c8705799811c5160f52b24767e43ac69be96c0c8944327786e40b2df1c

I now have to configure `EnforceMultipartRequestsPreflightHeader` to `false` to get file uploads to work. What is the purpose of `GraphQL-Preflight` header? Should it be sent by BCP and scripts in this scenario?

**Comment by kmcclellan** [comment]
I found the [context](https://github.com/ChilliCream/graphql-platform/issues/6188) and see this is related to CSRF. I'm not sure I follow how the header increases security though.

**Comment by tobias-tengler** [comment]
The problem is how browsers handle CORS preflight requests. 
Maybe you have seen the OPTIONS request in your Dev Tools at one point. That's the CORS preflight request that asks the server whether the browser is allowed to issue the next request to your server. If this preflight request doesn't succeed, because the origin it is being issued from is not allowed for example, the request won't even be sent to the server.
This preflight request isn't always sent though, particularly not for "simple" requests[^1].
At a basic level a simple request is a request that doesn't contain any user-defined headers. So you can issue a simple request through a form action for example. Let's say I'm an attacker and want to exploit this. If your server is using Cookies without the Same-Site restriction, I can craft a form like the following:

```html
<form action="http://myinsurance.com/graphql" method="post" enctype="multipart/form-data">
  <input type="hidden" name="operations" value='{ "query": "mutation { deleteMyAccount }", "variables": {} }' />
  <input type="hidden" name="map" value="{}" />
  <button type="submit">Get a free car!!!</button>
</form>
```

If I get an unsuspecting victim to click on this on my origin ("someotherorigin.com") the mutation **will be executed** on the server. My origin won't get to see the result because CORS determined I'm not allowed to, but at that point the action has already been executed. All because the browser determined it's a simple request and therefore doesn't send the CORS preflight request.

In order to address this, we must disallow any simple requests, because they could come from insecure origins. The simplest way is by forcing the request to contain a user-defined header. Remember that a user-defined header will "upgrade" the request from simple to mandating a preflight request.

Hope this explains it :)

[^1]: https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request (Paragraph 3)
