### ISSUE TITLE
An error "JSON cannot deserialize the given value." when use Federation and JsonType properties in the models of internal service

### ISSUE THREAD

**Issue by lev-smplt** [ChilliCream/graphql-platform#6364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

Hey guys. I have occured with strange behavior when using JsonType and federation.
So I have model on the internal service:
```
public class MyModel
{
    public long Id { get; set; }

    [GraphQLType(typeof(JsonType))]
    public string MyJson{ get; set; }
}
```
MyJson actually is `List<Hours>`. But in database it is stored like json string.
```
public class Hours
{
    public DayOfWeek Day { get; set; }
    public bool IsActive { get; set; }
    public TimeSpan? From { get; set; }
    public TimeSpan? To { get; set; }
}
```
When I'm fetching `MyModel` directly from internal service - it works fine, I recieve normal json response, but when I'm trying to fetch data via my external service, that is stitched with internal one, it says "JSON cannot deserialize the given value."

### Steps to reproduce

1. Configuration of internal service:

> - Model
> ```
> public class MyModel
> {
>     public long Id { get; set; }
> 
>     [GraphQLType(typeof(JsonType))]
>     public string MyJson{ get; set; }
> }
> ```

> - Query
> ```
> [QueryType]
> public class MyModelQueries
> {
>     [UsePaging(IncludeTotalCount = true)]
>     [UseProjection]
>     [UseFiltering]
>     [UseSorting]
>     public IQueryable<MyModel> MyModelSearch([Service] IMyModelRepository repository)
>     => repository.EntitySearch();
> }
> ```

> - Startup
> ```
>         services.AddMemoryCache();
>         services.AddGraphQLServer()
>                 .AddServiceTypes()
>                 .AddType(new TimeSpanType(TimeSpanFormat.DotNet))
>                 .AddProjections()
>                 .AddFiltering()
>                 .AddSorting()
>                 .AddInMemorySubscriptions()
>                 .InitializeOnStartup()
>                 .PublishSchemaDefinition(c => c
>                   .SetName("InternalService"));
> ```

2. Configuration of external service:
> -  Startup
> ```
>         services.AddHttpClient(
>             "InternalService",
>             c => c.BaseAddress = new Uri($"{InternalServiceUrl}/graphql"))
>
>         services.AddGraphQLServer()
>                 .AddRemoteSchema("InternalService")
>                 .AddType(new TimeSpanType(TimeSpanFormat.DotNet));
> ```

3. Make query on external service with fetching `MyJson`, that leads to "JSON cannot deserialize the given value." errror in response.

### Additional Context?

Platform: .Net6
Database: PostgreSQL
EFCore: Npgsql.EntityFrameworkCore.PostgreSQL 7.0.1
HotChocolate: 13.3.3

### Version

13.3.3

**Comment by michaelstaib** [comment]
We are no longer supporting HotChocolate.Stitching as it was replaces with 13 by HotChocolate.Fusion.

**Comment by mvarendorff** [comment]
Given that Stitching is still very much [at the forefront](https://chillicream.com/docs/hotchocolate/v13/distributed-schema/schema-stitching) of the documentation, I feel like this is a bit harsh. Arguably, I am biased, since I am facing the same problems as OP but two YouTube videos aside there is nothing available on Fusion yet:

![grafik](https://github.com/ChilliCream/graphql-platform/assets/80046268/db5ab233-e5e6-436e-955d-192000cd4959)

Is there really no chance this could be looked at?

**Comment by Vespersion** [comment]
I've also run into this issue, and given that it looks like this will never be looked at, and until Fusion has some better documentation and we can switch to it, I've found an intermediary solution.

In my case I was using the JSON type, with my underlying field being a JsonElement. What seems to be the problem is that the downstream service returns a JsonElement to the stitching request, but this response result is all serialized to a Dictionary, which means that the full JsonElement object is converted to a dictionary. In this case the stitching code doesn't seem to handle this situation and can't turn a dictionary into a JsonElement. I haven't used a string with the Json type but I imagine the problem is the same.

I've created an [IHttpStitchingRequestInterceptor](https://github.com/ChilliCream/graphql-platform/blob/main-version-12/src/HotChocolate/Stitching/src/Stitching/Pipeline/HttpStitchingRequestInterceptor.cs) to intercept the stitching response from the downstream service. Notably the `OnReceivedResultAsync()` method takes an `IQueryResult` argument which contains the data dictionary and returns an `IQueryResult`, which will override the result value with your returned value.

From here I just converted the dictionary representation of the JsonElement into an actual JsonElement and replaced the value in the result. Obviously the hard part here is finding the correct value in the result, but the method also takes an `IQueryRequest` which describes the query.

Extremely simplified code below:
```
public class GatewayHttpStitchingRequestInterceptor : IHttpStitchingRequestInterceptor
{
    public GatewayHttpStitchingRequestInterceptor()
    {
    }

    public ValueTask OnCreateRequestAsync(string targetSchema, IQueryRequest request, HttpRequestMessage requestMessage, CancellationToken cancellationToken = default)
    {
        return default;
    }

    public ValueTask<IQueryResult> OnReceivedResultAsync(string targetSchema, IQueryRequest request, IQueryResult result, HttpResponseMessage responseMessage, CancellationToken cancellationToken = default)
    {
        var entity = ((Dictionary<string, object>)result.Data["myEntity"]);
        var jsonValueDict = ((Dictionary<string, object>)entity["jsonField"]).ToDictionary(x => x.Key, x => ((IValueNode)x.Value).Value);
        var jsonValue = JsonSerializer.SerializeToDocument<Dictionary<string, object>>(jsonValueDict).RootElement;
        entity["jsonField"] = jsonValue;
        return new ValueTask<IQueryResult>(result);
    }
}
```

```
// Startup.cs

services.AddSingleton<IHttpStitchingRequestInterceptor, GatewayHttpStitchingRequestInterceptor>();
```

If my solution doesn't exactly solve your problem, you can at least use the stitching interceptor to debug what might be wrong with the result.

**Comment by lev-smplt** [comment]
@Vespersion, thank you for reply and provided solution. I will try that.

**Comment by mvarendorff** [comment]
We came up with a more generic solution for the problem that inspects the schema adding middlewares to correctly deserialize all remote JSON fields:

```cs
public class FixStitchedJsonTypeInterceptor : TypeInterceptor {
    public override void OnBeforeCompleteType(ITypeCompletionContext completionContext, DefinitionBase definition) {
        if (definition is not ObjectTypeDefinition { HasDirectives: true } objectTypeDefinition ||
            !objectTypeDefinition.Directives.Any(x => x.Type is NameDirectiveReference { Name: "source" })) {
            // Object is not from remote schema
            return;
        }

        foreach (var objectFieldDefinition in objectTypeDefinition.Fields) {
            if (objectFieldDefinition.Type is SyntaxTypeReference { Name: "JSON" }) {
                objectFieldDefinition.MiddlewareDefinitions.Add(new FieldMiddlewareDefinition(
                    _ => context => {
                        var parentDictionary = context.Parent<Dictionary<string, object>>();
                        parentDictionary.TryGetValue(context.Selection.ResponseName, out var value);
                        var unpacked = value is not null ? UnpackNodes(value) : value;
                        context.Result = JsonSerializer.SerializeToElement(unpacked);
                        return ValueTask.CompletedTask;
                    },
                    isRepeatable: true,
                    key: nameof(FixStitchedJsonTypeInterceptor)));
            }
        }
    }

    // Recursively unpacks `StringValueNode`s and the like into their corresponding primitive types.
    private static object UnpackNodes(object root) {
        var queue = new Queue<object>();
        var result = ProcessNode(root);

        while (queue.Count > 0) {
            var curr = queue.Dequeue();
            switch (curr) {
                case Dictionary<string, object> dict: {
                        foreach (var (key, value) in dict) {
                            dict[key] = ProcessNode(value);
                        }

                        break;
                    }
                case List<object> list: {
                        for (var i = 0; i < list.Count; i++) {
                            var value = list[i];
                            list[i] = ProcessNode(value);
                        }

                        break;
                    }
            }
        }

        return result;

        object ProcessNode(object node) {
            switch (node) {
                case Dictionary<string, object> dict: {
                        var clone = new Dictionary<string, object>(dict);
                        queue.Enqueue(clone);
                        return clone;
                    }
                case List<object> list: {
                        var clone = list.ToList();
                        queue.Enqueue(clone);
                        return clone;
                    }
                default:
                    return node switch {
                        StringValueNode stringValueNode => stringValueNode.Value,
                        BooleanValueNode booleanValueNode => booleanValueNode.Value,
                        IntValueNode intValueNode => intValueNode.ToInt64(),
                        FloatValueNode floatValueNode => floatValueNode.ToDouble(),
                        _ => node,
                    };
            }
        }
    }
}
```
