### ISSUE TITLE
feat: change visibility of TypeInterceptor.InitializeContext to public

### ISSUE THREAD

**Issue by dariuszkuc** [ChilliCream/graphql-platform#6656]
### Product

Hot Chocolate

### Is your feature request related to a problem?

`TypeInterceptor` provides a convenient mechanism that allows users to hook into various phases of a schema creation lifecycle. In order to be able to programmatically add new types it appears that we need access to the `IDescriptorContext`.

Existing type interceptors within the `HotChocolate` repository rely on `InitializeContext` hook which is an internal method. Alternatively, it was also possible to access the context from the public `OnBeforeCreateSchema` hook.

`HotChocolate` version 13.7.0 made a breaking change to the public hooks API and made `OnBeforeCreateSchema` hook internal.

### The solution you'd like

While existing schema builder hooks/type interceptor is getting deprecated in favor of a new mechanism. Existing hook mechanism should continue to work until the new mechanism is complete.

In order to not break existing clients, provide a mechanism to access the `IDescriptorContext`. 

Possible solutions
* change back visibility of `OnBeforeCreateSchema` to public
* open up `InitializeContext` hook to become public (seems more correct)

**Comment by michaelstaib** [comment]
Man, we are discussing this in the community now for month, to remove TypeInterceptor because it is. a horrible construct. We have tons of ordering issues with connecting features. Also initialisation wise from types. That is why we did drag a bit our feat feature wise since we have reached a breaking point. It works all because we have a platform approach ... everything is in this repo and everything we manage and keep working.

The solution is not the TypeInterceptor but Skimmed. We have done a lot of prototyping on this and it gets rid of the ordering issues and the complex handling of type references as you have a full mutable schema, no type references and stuff.

To be honest, we consider all of the repository one platform ... batteries included, we go farther than any other GraphQL framework and we move faster than most others as all the components fit together and we do not care about breaking stuff and moving forward. This means that all HC version since forever have to 100% align, but for the user this comes with benefits since everything just works.

The tilt towards Skimmed will be constant change in the type system for the next 6 month with tons of new features coming along like our new Data API 3.0.

You guys could also just have contributed it back instead of trying to move it out. You must have seen that while feature wise the apollo integration did not move it has constant changes to it with internal code being wired into it. To be honest you should have done the federation integration in place. While we did not have the bandwith to review federation related issues from users ... as this puts the burdon on us to review Apollos non existing spec definitions and to make sure it works in a Hot Chocolate way. But if Apollo employees want to openly contribute back this looks different.

From a platform aspect we will keep moving fast with 4 new spec drafts moving in the next week. We will do that without stopping or accommodating your needs as we have our own roadmap. But if you want to contribute back we will make sure that your PRs get quick pass into the repository.

I am closing this issue for now as we are not bringing these back.

**Comment by michaelstaib** [comment]
Just this last one, from an API side Skimmed will open the whole type initialization up, I hope that a big chunk will be merged over the weekend ... at the moment 60% of my work is going into this. We also have new hires starting that will go onto the project. It will make also our work with integrations much easier. We have two trials with the api already in Fusion and the Open API adapter for Hot Chocolate and give real flexibility.

**Comment by dariuszkuc** [comment]
Hello :wave:
While I didn't mention `ApolloGraphQL.HotChocolate.Federation` package, indeed this change does break our integration.

I also agree that using new `Skimmed.Schema` visitor might significantly simplify those integrations. That being said the underlying problem is that new APIs are still work in progress so folks cannot migrate to use them*. Since this is a change to the public API it also means that anyone extending `HotChocolate` that relies on this functionality (e.g. to abstract away application of some [custom directives](https://github.com/ChilliCream/graphql-platform/issues/6598) OR by adding some common queries/metadata like SDK version) is also broken.

*maybe I'm missing something obvious but I don't see a way to generate new skimmed schema from `IRequestExecutorBuilder`
