### ISSUE TITLE
DateTime type does not follow its own specification

### ISSUE THREAD

**Issue by cmeeren** [ChilliCream/graphql-platform#6887]
### Product

Hot Chocolate

### Version

13.8.1

### Link to minimal reproduction

See zip below

### Steps to reproduce

Repro solution: [HotChocolateBugRepro.zip](https://github.com/ChilliCream/graphql-platform/files/14240550/HotChocolateBugRepro.zip)

Relevant code:

```c#
public class Query
{
    public DateTimeOffset Date(DateTimeOffset dateTimeOffset) => dateTimeOffset;
}
```

When using `DateTimeOffset`, the schema contains this:

```graphql
"""
The `DateTime` scalar represents an ISO-8601 compliant date time type.
"""
scalar DateTime @specifiedBy(url: "https://www.graphql-scalars.com/date-time")
```

The spec on that URL gives examples of valid and invalid strings. **Currently, HotChocolate accepts half of the invalid patterns, and more.** This includes for example a date only (where the time will be taken to be midnight in the server's time zone, which is bad and can easily cause bugs and confusion for API clients - ask me how I know...).

It also accepts formats such as `2010/02/11` and `11.02.2010` (at least on my computer with my regional settings).

HotChocolate needs to be much stricter if it is to actually represent the linked `DateTime` type.

**Note that this may be relevant for other of HotChocolate's built-in scalars, too.** (I haven't checked, but I assume it applies to at least `DateTime`).

### What is expected?

Parsing conforms to the linked spec.

### What is actually happening?

Parsing is much more lenient than the linked spec and accepts invalid input.

**Comment by cmeeren** [comment]
This is mistakenly labelled `Area: F#`. The repro code is C#.

**Comment by cmeeren** [comment]
This is improved in 14.0.0-rc.0, but there is still not perfect overlap with the valid/invalid patterns in https://www.graphql-scalars.com/date-time.

**Comment by glen-84** [comment]
@cmeeren Could you please provide some examples? We do have [tests](https://github.com/ChilliCream/graphql-platform/blob/91fc947cb802668114aa78fbfd7ccd245a55503b/src/HotChocolate/Core/test/Types.Tests/Types/Scalars/DateTimeTypeTests.cs#L424-L484) for the valid and invalid date/times.

**Comment by cmeeren** [comment]
It's about the requirement of exactly three digits millisecond part. The value `2011-08-30T13:22:53.108912Z` is listed as invalid on the spec page, but passes the repro solution (when updated to rc.0).

**Comment by cmeeren** [comment]
Additionally, the spec page lists `2011-08-30T24:22:53Z` as an invalid value because "Fractions of a second are missing", but that value is primarily invalid (at least in HC) because the hour is `24`. If you try a valid date-time without exactly three fractional seconds, such as `2011-08-30T13:22:53.10Z` or `2011-08-30T13:22:53Z`, they are also considered valid in rc.0, but should not be valid according to the spec.

**Comment by glen-84** [comment]
This is intentional:

- https://github.com/ChilliCream/graphql-platform/blob/91fc947cb802668114aa78fbfd7ccd245a55503b/src/HotChocolate/Core/test/Types.Tests/Types/Scalars/DateTimeTypeTests.cs#L464-L465
- https://github.com/ChilliCream/graphql-platform/blob/91fc947cb802668114aa78fbfd7ccd245a55503b/website/src/docs/hotchocolate/v14/migrating/migrate-from-13-to-14.md#datetime-scalar-enforces-a-specific-format

We felt that requiring a fixed 3 fractional digits was unnecessarily arbitrary, and inconsistent with RFC 3339. We made fractional seconds optional (as they are in RFC 3339), but decided to limit them to 7, as most languages support 7 or fewer digits of precision.

[An issue](https://github.com/andimarek/graphql-scalars.com/issues/2) has been raised before regarding the number and requirement for fractional seconds.

It's not ideal to have this "specified by" URL pointing to a specification that isn't a 100% match, but Michael did mention that he may discuss this with Andi.

Regardless, I'll add a note to the documentation about this difference next week.

**Comment by cmeeren** [comment]
Thanks for the clarification! Feel free to close this issue.
