### ISSUE TITLE
Documentation for Hotchocolate.AspNetClassic 

### ISSUE THREAD

**Issue by briantolsen** [ChilliCream/graphql-platform#6931]
### Product

Hot Chocolate

### Is your feature request related to a problem?

Yes, there is no clear documentation on how to implement an GraphQL API using .Net Framework using Hotchocolate.AspNetClassic or with Hotchocolate v10. 

### The solution you'd like

Please provide an example or documentation for the HotChocolate.AspNetClassic library.

**Comment by PascalSenn** [comment]
HotChocolate V10 is a 4 year old version. The framework has evolved a lot since then and `.NET Framework 4.X.X` support was dropped already a long time ago. 

Since `v10` is not supported anymore i do strongly advise you to not use it and instead use a newer version.
But there are in fact still docs for v10 around:  https://chillicream.com/docs/hotchocolate/v10
