### ISSUE TITLE
Unused optional filter input adds weirdly high cost

### ISSUE THREAD

**Issue by Healios** [ChilliCream/graphql-platform#7658]
### Product

Hot Chocolate

### Version

14.0.0

### Link to minimal reproduction

https://github.com/Healios/OptionalInputFilterCostIssue

### Steps to reproduce

1. Run reproduction.
2. Run below query in one document (with GraphQL-cost: report):
```
query readContactCount {
  readAllContacts(skip: 0, take: 1, where: null) {
    totalCount
  }
}
```
3. Run below query in another document (with GraphQL-cost: report):
```
query readContactCount($where: ContactFilterInput) {
  readAllContacts(skip: 0, take: 1, where: $where) {
    totalCount
  }
}
```
4. Compare costs.

### What is expected?

I would have expected the cost to basically be the same.

### What is actually happening?

The cost of the first query is 21, while the cost of the second is 911

### Additional context

In my frontend, I'm using Urql & @graphql-codegen. I need the second query in order to get the total count of contacts based on a dynamic/varying filter.

**Comment by Jacob-Steentoft** [comment]
We're seeing similar issues on our end as well after upgrading to version 14. The following query:

```
query ($resourceFilter: ResourceEntityFilterInput!) {
  resources(skip: 0, take: 1, where: $resourceFilter) {
    items {
      id
      resourceModel {
        id
        icon
        description
        modifiedAt
        category
        name
      }
    }
  }
}
```

```
{
  "resourceFilter":{
    "id": {
      "eq" : "cccc389a-a58f-ef11-8a6a-002248a27830"
    }
  } 
}
```

Produces a field cost of 5462 which seems too high for the simplicity of the query itself.

**Comment by michaelstaib** [comment]
This is correct. Think about the following, by not specifying the where all filter combination with all or combinations are possible. Instead of allowing all possibilities reduce the impact of your filter:

```
query ($description: String!) {
  resources(skip: 0, take: 1, where: { resourceModel { description: { contains: $description } }) {
    items {
      id
      resourceModel {
        id
        icon
        description
        modifiedAt
        category
        name
      }
    }
  }
}
```

The cost just tells you the truth here as the query can be used to do anything, which translates to your database. For someone with malicious intent its very east to take down your server or the very least to create very expensive operations that transalte 1:1 to your database.

Things you should consider.

- Disable connector like OR (OR is considered a multiplier of cost)
- Disable operation kinds that you do not need (Create filter inputs and remove operations like `containes` or `startsWith`)
- Specify precise operations
